service: minigamesDB 

provider:
  name: aws
  runtime: nodejs20.x  
  region: eu-west-3  

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origins:
              - "*" 
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allowCredentials: true  
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - "*" 
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allowCredentials: true  
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: '*'
