service: minigamesDB 

provider:
  name: aws
  runtime: nodejs20.x  # El runtime que estás usando (ajusta según tu versión de Node.js)
  region: eu-west-3  

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: '*'
